# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12c350d25622087823981bac90c04702bcd17ff9ebb344a7c2614bc14fd05c95970ad414ac385bcc1f3d741b9efae17e4a1ba16a4e5d7d935e6b8163cc2ff47b

test:
  secret_key_base: 7341a6616d1b426d448bc3608cfa7e81502732f424d2991b61655f72ace02018be0e1ed93aaf5865c22007e6ba0807011fab3e75865648682c5ca864048354d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
